os: linux
language: c
arch: amd64

notifications:
  email: false

# 1. Build and load `/dev/sgx-step`
before_install:
    - sudo apt-get update
    - cd $TRAVIS_BUILD_DIR/kernel/
    - bash -x ./install_SGX_driver.sh
    - make clean load

# 2. Patch and install SGX SDK
install:
    - cd $TRAVIS_BUILD_DIR/sdk/intel-sdk/
    - bash -x ./install_SGX_SDK.sh
    - source /opt/intel/sgxsdk/environment
    - sudo service aesmd status
    - cd linux-sgx/SampleCode/LocalAttestation
    - make SGX_MODE=SIM
    - cd bin
    - ./app

# 3. Build test applications
script:
    - for d in $TRAVIS_BUILD_DIR/app/*/ ; do echo -e "\n**** $d ****\n" ; cd "$d" ; make ; done

jobs:
    include:
       - dist: bionic   # 18.04
       - dist: focal    # 20.04
