[package]
name = "sgx-urts-sys"
version = "0.1.0"
edition = "2021"

[features]

# HW mode
default = []

# SW mode
# default = ["sim"]

sim = []

[dependencies]

[build-dependencies]
cc = "1.0"
glob = "0.3"
bindgen = "0.69"
