#include "sgx_tracer.h"

/* Internal (ugly functions)*/
static void generate_ids(char (*ids)[4], size_t count);

/* When creating a new module assign */
static const create_module_fn module_factory[] = {
        [PAGES] = trace_pages_create,
        [GPRS]  = trace_gprs_create,
        [IRQ]   = trace_irq_create,
    };

/* 
    NOTE: Always call sgx_tracer_init even when all module items 
          Even when all modules require specific items. Just leave
          the options empty in the init and then call manual add with
          the items
*/

void sgx_tracer_init(sgx_tracer_t *t)
{
    t->num_modules = 0;
}

void sgx_tracer_trace_all(sgx_tracer_t *t, const track_type_t *options, size_t opt_cnt)
{

    ASSERT(t->num_modules + opt_cnt < MAX_MODULES);

    for (size_t i = 0; i < opt_cnt; i++)
    {
        /* get init from factory */
        create_module_fn create = module_factory[options[i]];
        ASSERT( create != NULL);

        /* create the module */
        trace_module_t *m = create();
        ASSERT( m != NULL );
    
        /* init the state */
        void *s = m->init();
        ASSERT( s != NULL);

        t->modules[t->num_modules++] = (tracer_entry_t) { .module = m, .state = s};
    }
}

void sgx_tracer_enable(sgx_tracer_t *t, track_type_t opt)
{
    ASSERT(t->num_modules < MAX_MODULES);

    /* get init from factory */
    create_module_fn create = module_factory[opt];
    ASSERT( create != NULL);

    /* create the module */
    trace_module_t *m = create();
    ASSERT( m != NULL );
    
    /* init the state */
    void *s = m->init();
    ASSERT( s != NULL);

    t->modules[t->num_modules++] = (tracer_entry_t) { .module = m, .state = s};
}

/* Manually add module to specify which items to track */
void sgx_tracer_man_add(sgx_tracer_t *t, track_type_t opt, void *items, size_t num_of_items)
{
    ASSERT(t->num_modules < MAX_MODULES);

    /* get init from factory */
    create_module_fn create = module_factory[opt];
    ASSERT( create != NULL);

    /* create the module */
    trace_module_t *m = create();
    ASSERT( m != NULL );

    /* Init state but specific items */
    void *s = m->man_init(items, num_of_items);
    ASSERT( s != NULL);

    t->modules[t->num_modules++] = (tracer_entry_t) { .module = m, .state = s};
}

void sgx_tracer_update(sgx_tracer_t *t)
{
    if (t->step_count > MAX_STEPS)
        return;

    for (size_t i = 0; i < t->num_modules; i++) 
    {
        // call the update function of each module.
        // Give argument the module (self)
        t->modules[i].module->update(t->modules[i].state);
    }
    t->step_count++;
}

void sgx_tracer_destroy(sgx_tracer_t *t)
{
    for (size_t i = 0; i < t->num_modules; i++) 
    {
        /* Free module state & module object*/
        t->modules[i].module->destroy(t->modules[i].state);
        free(t->modules[i].module);
        t->num_modules = 0;
    }
}

void sgx_tracer_vcd(sgx_tracer_t *t)
{
    FILE *f = fopen("sgx_tracer_log.vcd", "w");
    if (!f) 
    {
        perror("(write_vcd) fopen error");
        return;
    }
    char date_buf[64];
    time_t now = time(NULL);
    struct tm *tm_info = localtime(&now);
    strftime(date_buf, sizeof(date_buf), "%a %b %d %H:%M:%S %Y", tm_info);

    // ========================= Header ============================= //
    fprintf(f, "$version\n\tGenerated by SGX-step\n$end\n");
    fprintf(f, "$date\n\t%s\n$end\n", date_buf);
    fprintf(f, "$timescale 1ns $end\n");

    /* Module grouping */
    fprintf(f, "$scope module top $end\n");

    size_t total_items = 0;

    /* find the items to create id array */
    for (size_t i = 0; i < t->num_modules; i++)
    {
        total_items += t->modules[i].module->count(t->modules[i].state);
    }
    char (*ids)[4] = malloc(total_items * sizeof(*ids));
    ASSERT(ids != NULL);
    generate_ids(ids, total_items);

    size_t id_index = 0;
    for (size_t i = 0; i < t->num_modules; i++)
    {
        tracer_entry_t t_entry = t->modules[i];
        trace_module_t *mod = t_entry.module;
        void *s = t_entry.state;
        trace_signal_t sig;

        fprintf(f, "$scope module %s $end\n", t->modules[i].module->module_name);
        ASSERT( mod->get(s, 0, &sig) == 0 );

        //size_t items = mod->count(s); 

        for (size_t j = 0; j < sig.items; j++)
        {
            char name[32];
            mod->describe(s, j, name);
            fprintf(f, "$var wire %zu %s %s $end\n",
                sig.bits_per_item,  
                ids[id_index],            
                name);
            id_index++;
        }

        fprintf(f, "$upscope $end\n");
    }
    
    fprintf(f, "$upscope $end\n");
    fprintf(f, "$enddefinitions $end\n");


    /* =================== Initial values ======================= */
    fprintf(f, "#0\n"); // Time step 0
    id_index = 0;
    for (size_t m_i = 0; m_i < t->num_modules; m_i++)
    {
        tracer_entry_t t_entry = t->modules[m_i];
        trace_module_t *mod = t_entry.module;
        void *s = t_entry.state;
        //size_t items = mod->count(s);

        trace_signal_t sig;
        ASSERT(mod->get(s, 0, &sig) == 0);
        size_t bits_per_item = sig.bits_per_item;

        for (size_t i = 0; i < sig.items; i++)
        {
            fprintf(f, "b");
            for (size_t b = 0; b < bits_per_item; b++)
                fputc('0', f);

            fprintf(f, " %s\n", ids[id_index]);
            id_index++;
        }
    }

    /* ================ Value Changes ===================== */

    /* Initialize prev_states */
    uint8_t **prev_values = malloc(t->num_modules * sizeof(uint8_t *));
    for (size_t m = 0; m < t->num_modules; m++)
    {
        tracer_entry_t entry = t->modules[m];
        trace_module_t *mod = entry.module;
        void *s = entry.state;

        trace_signal_t sig;
        ASSERT(mod->get(s, 0, &sig) == 0);

        /* Array of arrays */
        prev_values[m] = calloc((sig.items * sig.bits_per_item + 7) / 8, 1); 
    }

    /* Do value changes in vcd... */
    for (size_t step = 1; step < t->step_count; step++)
    {
        id_index = 0; /* reset index for each step */
        fprintf(f, "#%zu\n", step);
        for (size_t m = 0; m < t->num_modules; m++)
        {
            tracer_entry_t entry = t->modules[m];
            trace_module_t *mod = entry.module;
            void *s = entry.state;

            trace_signal_t sig;
            ASSERT(mod->get(s, step, &sig) == 0);

            uint8_t *curr = (uint8_t *)sig.payload;
            //uint64_t *check = (uint64_t *)sig.payload;
            uint8_t *prev = prev_values[m];

            size_t width_bytes = (sig.items * sig.bits_per_item + 7) / 8;

            /* Quick filter over all but should always be true in principal */
            //if (memcmp(curr, prev, width_bytes) != 0)
            //{
            size_t bits_per_item = sig.bits_per_item;

            for (size_t i = 0; i < sig.items; i++)
            {
                uint64_t curr_val = 0;
                uint64_t prev_val = 0;

                /* Extctract bits of the signal */
                for (size_t b = 0; b < bits_per_item; b++)
                {
                    size_t bit_index = bits_per_item * i + b;
                    size_t byte = bit_index / 8;
                    size_t off = bit_index % 8;
                    
                    if (curr[byte] & ((uint8_t)1 << off))
                    {
                        curr_val |= ((uint64_t)1 << b); /* b must not surpass 64 */
                    }

                    if (prev[byte] & ((uint8_t)1 << off))
                        prev_val |= ((uint64_t)1 << b);
                }

                if (curr_val != prev_val)
                {
                    fprintf(f, "b");

                    /* VCD thingy */
                    for (ssize_t b = bits_per_item - 1; b >= 0; b--)
                    {
                        fputc((curr_val >> b) & 1 ? '1' : '0', f);
                    }
                    fprintf(f, " %s\n", ids[id_index]);
                }
                id_index++; 
            }
            memcpy(prev, curr, width_bytes); /* curr is the new prev */
            //}
            //else
            //{
            //    /* Skip these items nothing changed */
            //    id_index += sig.items;
            //}
        }
    }

    // free ids, prev_states, close fd (dynamic array)
    fclose(f);
    free(ids);
    for (size_t m = 0; m < t->num_modules; m++)
        free(prev_values[m]);
    free(prev_values);
}

/* ================ Internal functions ========================= */
static void generate_ids(char (*ids)[4], size_t count)
{
    static const char alphabet[] =
    "!\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~";

    const size_t base = sizeof(alphabet) - 1;

    for (size_t i = 0; i < count; i++)
    {
        ids[i][0] = alphabet[i % base];
        ids[i][1] = alphabet[(i / base) % base];
        ids[i][2] = alphabet[(i / (base * base)) % base];
        ids[i][3] = '\0';
    }
}
/* ============================================================= */